targets:
  japan:
    game_code: BPGJ
    region: Japan
    language: Japanese
    sha1: 5946f1b59e8d71cc61249661464d864185c92a5f
  usa:
    game_code: BPGE
    region: USA
    language: English
    sha1: 574fa542ffebb14be69902d1d36f1ec0a4afd71e
  europe_rev1:
    game_code: BPGE
    region: Europe
    language: English
    revision: 1
    sha1: 7862c67bdecbe21d1d69ce082ce34327e1c6ed5e
  germany:
    game_code: BPGD
    region: Germany
    language: German
    sha1: 0802d1fb185ee3ed48d9a22afb25e66424076dac
  france:
    game_code: BPGF
    region: France
    language: French
    sha1: 4b5758c14d0a07b70ef3ef0bd7fa5e7ce6978672
  italy:
    game_code: BPGI
    region: Italy
    language: Italian
    sha1: a1dfea1493d26d1f024be8ba1de3d193fcfc651e
  spain:
    game_code: BPGS
    region: Spain
    language: Spanish
    sha1: f9ebee5d228cb695f18ef2ced41630a09fa9eb05
